spring:
  application:
    name: library-management-system

  profiles:
    active: dev   # 개발용 설정 (ddl-auto: create => update, validate)

  output:
    ansi:
      enabled: detect   # 자동 감지하여 컬러 출력

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver #Mysql db 드라이버
    username: root
    password: 12345
    url: jdbc:mysql://localhost:3306/librarydb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8

  # 파일 업로드 설정
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

server:
  port: 8081

# 파일 저장 경로
file:
  upload-dir: ./uploads




---
#개발 환경 설정
spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

#로깅 설정
logging:
  file:
    name: logs/library-system.log   # 로그 파일 저장 설정

  level:
    com.library: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.tool.schema.internal.exec: WARN
    org.hibernate.tool.schema.extract: WARN

---
#운영 환경 설정
spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: validate    # 운영환경에서는 검증만
    show-sql: false         # 운영환경에서는 SQL 출력 안함